//==============================================================================
//  WARNING!!  This file is overwritten by the Block UI Styler while generating
//  the automation code. Any modifications to this file will be lost after
//  generating the code again.
//
//       Filename:  C:\Users\86187\Desktop\拼料插件\UI1.cpp
//
//        This file was generated by the NX Block UI Styler
//        Created by: 86187
//              Version: NX 2306
//              Date: 04-13-2026  (Format: mm-dd-yyyy)
//              Time: 17:52 (Format: hh-mm)
//
//==============================================================================

//==============================================================================
//  Purpose:  This TEMPLATE file contains C++ source to guide you in the
//  construction of your Block application dialog. The generation of your
//  dialog file (.dlx extension) is the first step towards dialog construction
//  within NX.  You must now create a NX Open application that
//  utilizes this file (.dlx).
//
//  The information in this file provides you with the following:
//
//  1.  Help on how to load and display your Block UI Styler dialog in NX
//      using APIs provided in NXOpen.BlockStyler namespace
//  2.  The empty callback methods (stubs) associated with your dialog items
//      have also been placed in this file. These empty methods have been
//      created simply to start you along with your coding requirements.
//      The method name, argument list and possible return values have already
//      been provided for you.
//==============================================================================

//------------------------------------------------------------------------------
//These includes are needed for the following template code
//------------------------------------------------------------------------------
#include "UI1.hpp"
using namespace NXOpen;
using namespace NXOpen::BlockStyler;

//------------------------------------------------------------------------------
// Constructor for NX Styler class
//------------------------------------------------------------------------------
// Initialize static variables
Session* (UI1::theSession) = NULL;
UI* (UI1::theUI) = NULL;
// Constructor for NX Styler class
UI1::UI1()
{
    try
    {
        // Initialize the NX Open C++ API environment
        UI1::theSession = NXOpen::Session::GetSession();
        UI1::theUI = UI::GetUI();
        theDlxFileName = "UI1.dlx";
        theDialog = UI1::theUI->CreateDialog(theDlxFileName);
        // Registration of callback functions
        theDialog->AddApplyHandler(make_callback(this, &UI1::apply_cb));
        theDialog->AddOkHandler(make_callback(this, &UI1::ok_cb));
        theDialog->AddUpdateHandler(make_callback(this, &UI1::update_cb));
        theDialog->AddInitializeHandler(make_callback(this, &UI1::initialize_cb));
        theDialog->AddDialogShownHandler(make_callback(this, &UI1::dialogShown_cb));

        boundingBoxBody = NULL;
    }
    catch (exception& ex)
    {
        //---- Enter your exception handling code here -----
        throw;
    }
}
// Destructor for NX Styler class
UI1::~UI1()
{
    if (theDialog != NULL)
    {
        delete theDialog;
        theDialog = NULL;
    }
}
//------------------------------- DIALOG LAUNCHING ---------------------------------
extern "C" DllExport void  ufusr(char* param, int* retcod, int param_len)
{
    UI1* theUI1 = NULL;
    UF_initialize();
    try
    {
        theUI1 = new UI1();
        // The following method shows the dialog immediately
        theUI1->Launch();
    }
    catch (exception& ex)
    {
        //---- Enter your exception handling code here -----
        UI1::theUI->NXMessageBox()->Show("Block Styler", NXOpen::NXMessageBox::DialogTypeError, ex.what());
    }
    if (theUI1 != NULL)
    {
        delete theUI1;
        theUI1 = NULL;
    }
    UF_terminate();
}
extern "C" DllExport int ufusr_ask_unload()
{
    //return (int)Session::LibraryUnloadOptionExplicitly;
    return (int)Session::LibraryUnloadOptionImmediately;
    //return (int)Session::LibraryUnloadOptionAtTermination;
}
// Following method cleanup any housekeeping chores that may be needed.
// This method is automatically called by NX.
extern "C" DllExport void ufusr_cleanup(void)
{
    try
    {
        //---- Enter your callback code here -----
    }
    catch (exception& ex)
    {
        //---- Enter your exception handling code here -----
        UI1::theUI->NXMessageBox()->Show("Block Styler", NXOpen::NXMessageBox::DialogTypeError, ex.what());
    }
}
//This method launches the dialog to screen
NXOpen::BlockStyler::BlockDialog::DialogResponse UI1::Launch()
{
    NXOpen::BlockStyler::BlockDialog::DialogResponse dialogResponse = NXOpen::BlockStyler::BlockDialog::DialogResponse::DialogResponseInvalid;
    try
    {
        dialogResponse = theDialog->Launch();
    }
    catch (exception& ex)
    {
        //---- Enter your exception handling code here -----
        UI1::theUI->NXMessageBox()->Show("Block Styler", NXOpen::NXMessageBox::DialogTypeError, ex.what());
    }
    return dialogResponse;
}
//---------------------Block UI Styler Callback Functions--------------------------
//Callback Name: initialize_cb
void UI1::initialize_cb()
{
    try
    {
        ui_group1 = dynamic_cast<NXOpen::BlockStyler::Group*>(theDialog->TopBlock()->FindBlock("ui_group1"));
        ui_button0 = dynamic_cast<NXOpen::BlockStyler::Button*>(theDialog->TopBlock()->FindBlock("ui_button0"));
        ui_group2 = dynamic_cast<NXOpen::BlockStyler::Group*>(theDialog->TopBlock()->FindBlock("ui_group2"));
        ui_selection0 = dynamic_cast<NXOpen::BlockStyler::SelectObject*>(theDialog->TopBlock()->FindBlock("ui_selection0"));
        ui_point0 = dynamic_cast<NXOpen::BlockStyler::SpecifyPoint*>(theDialog->TopBlock()->FindBlock("ui_point0"));
        ui_toggle0 = dynamic_cast<NXOpen::BlockStyler::Toggle*>(theDialog->TopBlock()->FindBlock("ui_toggle0"));
        ui_group3 = dynamic_cast<NXOpen::BlockStyler::Group*>(theDialog->TopBlock()->FindBlock("ui_group3"));
        ui_linear_dim0 = dynamic_cast<NXOpen::BlockStyler::LinearDimension*>(theDialog->TopBlock()->FindBlock("ui_linear_dim0"));
        ui_linear_dim01 = dynamic_cast<NXOpen::BlockStyler::LinearDimension*>(theDialog->TopBlock()->FindBlock("ui_linear_dim01"));
        ui_linear_dim02 = dynamic_cast<NXOpen::BlockStyler::LinearDimension*>(theDialog->TopBlock()->FindBlock("ui_linear_dim02"));
        ui_toggle01 = dynamic_cast<NXOpen::BlockStyler::Toggle*>(theDialog->TopBlock()->FindBlock("ui_toggle01"));
    }
    catch (exception& ex)
    {
        //---- Enter your exception handling code here -----
        UI1::theUI->NXMessageBox()->Show("Block Styler", NXOpen::NXMessageBox::DialogTypeError, ex.what());
    }
}
//Callback Name: dialogShown_cb
void UI1::dialogShown_cb()
{
    try
    {
        //---- Enter your callback code here -----
    }
    catch (exception& ex)
    {
        //---- Enter your exception handling code here -----
        UI1::theUI->NXMessageBox()->Show("Block Styler", NXOpen::NXMessageBox::DialogTypeError, ex.what());
    }
}
//Callback Name: apply_cb
int UI1::apply_cb()
{
    int errorCode = 0;
    try
    {
        // 获取选中的对象
        std::vector<TaggedObject*> selectedObjects = ui_selection0->GetSelectedObjects();

        if (selectedObjects.empty())
        {
            UI1::theUI->NXMessageBox()->Show("提示", NXOpen::NXMessageBox::DialogTypeInformation, "请选择至少一个实体！");
            return 1;
        }

        // 过滤出实体对象
        std::vector<NXOpen::Body*> bodies;
        for (size_t i = 0; i < selectedObjects.size(); i++)
        {
            NXOpen::Body* body = dynamic_cast<NXOpen::Body*>(selectedObjects[i]);
            if (body != NULL && body->IsSolidBody())
            {
                bodies.push_back(body);
            }
        }

        if (bodies.empty())
        {
            UI1::theUI->NXMessageBox()->Show("提示", NXOpen::NXMessageBox::DialogTypeInformation, "未选择有效的实体！");
            return 1;
        }

        // 检查是否启用排样功能
        bool enableNesting = ui_toggle01->Value();

        if (enableNesting)
        {
            // 功能2：计算最大包容轮廓（排样）
            theSession->ListingWindow()->WriteLine("=== 开始排样计算 ===");

            // 存储每个实体的包围盒信息 [minX, minY, minZ, maxX, maxY, maxZ, length, width]
            struct BodyInfo {
                NXOpen::Body* body;
                double box[6];
                double length; // X方向尺寸
                double width;  // Y方向尺寸
                double originalMinZ;
            };

            std::vector<BodyInfo> bodyInfos;

            // 获取每个实体的包围盒
            for (size_t i = 0; i < bodies.size(); i++)
            {
                BodyInfo info;
                info.body = bodies[i];
                tag_t bodyTag = bodies[i]->Tag();

                // 使用UF函数获取包围盒
                UF_MODL_ask_bounding_box(bodyTag, info.box);

                info.length = info.box[3] - info.box[0]; // maxX - minX
                info.width = info.box[4] - info.box[1];  // maxY - minY
                info.originalMinZ = info.box[2];

                bodyInfos.push_back(info);

                char msg[256];
                sprintf(msg, "实体 %zu: 长=%.2f, 宽=%.2f, X范围[%.2f, %.2f], Y范围[%.2f, %.2f]",
                    i + 1, info.length, info.width,
                    info.box[0], info.box[3], info.box[1], info.box[4]);
                theSession->ListingWindow()->WriteLine(msg);
            }

            // 按宽度排序（可选优化）
            std::sort(bodyInfos.begin(), bodyInfos.end(),
                [](const BodyInfo& a, const BodyInfo& b) {
                    return a.width > b.width; // 宽度大的优先
                });

            // 排样算法：沿X轴紧密排列
            double currentX = 0.0;
            double currentY = 0.0;
            double maxYInRow = 0.0;
            double rowStartX = 0.0;
            double maxRowHeight = 0.0;

            const double gap = 0.0; // 实体间间隙

            for (size_t i = 0; i < bodyInfos.size(); i++)
            {
                BodyInfo& info = bodyInfos[i];

                // 计算移动后的位置
                double targetMinX = currentX;
                double targetMinY = currentY;

                // 计算需要移动的距离
                double moveX = targetMinX - info.box[0];
                double moveY = targetMinY - info.box[1];
                double moveZ = -info.originalMinZ; // 移动到Z=0

                theSession->ListingWindow()->WriteLine(NXString("实体 " + std::to_string(i + 1) +
                    " 移动: dX=" + std::to_string(moveX) +
                    ", dY=" + std::to_string(moveY) +
                    ", dZ=" + std::to_string(moveZ)));

                // 使用UF_MODL_move_feature移动实体
                tag_t bodyTag = info.body->Tag();
                uf_list_p_t feature_list = NULL;
                UF_MODL_ask_body_feats(bodyTag, &feature_list);

                if (feature_list != NULL)
                {
                    // 设置移动数据（POINT_TO_POINT模式）
                    double real_data[2][12];
                    // 初始化所有数据为0
                    for (int m = 0; m < 2; m++)
                    {
                        for (int n = 0; n < 12; n++)
                        {
                            real_data[m][n] = 0.0;
                        }
                    }
                    // 初始点
                    real_data[0][0] = info.box[0];
                    real_data[0][1] = info.box[1];
                    real_data[0][2] = info.box[2];
                    // 目标点
                    real_data[1][0] = info.box[0] + moveX;
                    real_data[1][1] = info.box[1] + moveY;
                    real_data[1][2] = info.box[2] + moveZ;

                    // 移动特征
                    UF_MODL_move_feature(feature_list, 0, real_data);

                    // 清理列表
                    UF_MODL_delete_list(&feature_list);
                }

                // 更新包围盒信息
                info.box[0] += moveX;
                info.box[3] += moveX;
                info.box[1] += moveY;
                info.box[4] += moveY;
                info.box[2] += moveZ;
                info.box[5] += moveZ;

                // 更新当前位置
                currentX = info.box[3] + gap;

                // 更新行最大高度
                if (info.width > maxRowHeight)
                {
                    maxRowHeight = info.width;
                }
            }

            // 更新部件
            UF_MODL_update();

            // 计算总包围盒
            double totalMinX = 1e30, totalMinY = 1e30, totalMinZ = 1e30;
            double totalMaxX = -1e30, totalMaxY = -1e30, totalMaxZ = -1e30;

            for (size_t i = 0; i < bodyInfos.size(); i++)
            {
                if (bodyInfos[i].box[0] < totalMinX) totalMinX = bodyInfos[i].box[0];
                if (bodyInfos[i].box[1] < totalMinY) totalMinY = bodyInfos[i].box[1];
                if (bodyInfos[i].box[2] < totalMinZ) totalMinZ = bodyInfos[i].box[2];
                if (bodyInfos[i].box[3] > totalMaxX) totalMaxX = bodyInfos[i].box[3];
                if (bodyInfos[i].box[4] > totalMaxY) totalMaxY = bodyInfos[i].box[4];
                if (bodyInfos[i].box[5] > totalMaxZ) totalMaxZ = bodyInfos[i].box[5];
            }

            double totalLength = totalMaxX - totalMinX;
            double totalWidth = totalMaxY - totalMinY;
            double totalHeight = totalMaxZ - totalMinZ;

            char totalMsg[256];
            sprintf(totalMsg, "总包围盒: 长=%.2f, 宽=%.2f, 高=%.2f", totalLength, totalWidth, totalHeight);
            theSession->ListingWindow()->WriteLine(totalMsg);

            // 创建透明包围盒
            if (ui_toggle0->Value())
            {
                // 删除旧的包围盒
                if (boundingBoxBody != NULL)
                {
                    tag_t bboxTag = boundingBoxBody->Tag();
                    UF_OBJ_delete_object(bboxTag);
                    boundingBoxBody = NULL;
                }

                // 使用UF函数创建块特征
                double origin[3] = { totalMinX, totalMinY, totalMinZ };
                char* edge_len[3];
                char len0[256], len1[256], len2[256];
                sprintf(len0, "%f", totalLength);
                sprintf(len1, "%f", totalWidth);
                sprintf(len2, "%f", totalHeight);
                edge_len[0] = len0;
                edge_len[1] = len1;
                edge_len[2] = len2;

                tag_t blockTag;
                int errorCode_uf = UF_MODL_create_block1(UF_NULLSIGN, origin, edge_len, &blockTag);

                if (errorCode_uf == 0)
                {
                    boundingBoxBody = dynamic_cast<NXOpen::Body*>(NXObjectManager::Get(blockTag));
                    theSession->ListingWindow()->WriteLine("已创建透明包围盒");

                    // 设置包围盒透明度
                    if (boundingBoxBody != NULL)
                    {
                        std::vector<DisplayableObject*> objects;
                        objects.push_back(boundingBoxBody);

                        DisplayManager* displayManager = theSession->DisplayManager();
                        DisplayModification* displayModification = displayManager->NewDisplayModification();

                        displayModification->SetNewTranslucency(70); // 设置透明度为70%
                        displayModification->Apply(objects);

                        delete displayModification;
                    }
                }
            }

            // 功能3：移动与显示 - 存储移动后的实体
            movedBodies.clear();
            for (size_t i = 0; i < bodyInfos.size(); i++)
            {
                movedBodies.push_back(bodyInfos[i].body);
            }

            theSession->ListingWindow()->WriteLine("=== 排样计算完成 ===");
            UI1::theUI->NXMessageBox()->Show("完成", NXOpen::NXMessageBox::DialogTypeInformation,
                NXString("排样完成！总尺寸: 长=" + std::to_string(totalLength) +
                    ", 宽=" + std::to_string(totalWidth) +
                    ", 高=" + std::to_string(totalHeight)));
        }
        else
        {
            // 功能1：实体选择与基准面对齐（原有逻辑）
            for (size_t i = 0; i < bodies.size(); i++)
            {
                NXOpen::Body* body = bodies[i];

                // 获取实体的所有面
                std::vector<NXOpen::Face*> faces = body->GetFaces();

                if (faces.empty())
                {
                    continue;
                }

                // 找到底面（最小Z值的面）
                NXOpen::Face* bottomFace = NULL;
                double minZ = 1e30;

                for (size_t j = 0; j < faces.size(); j++)
                {
                    NXOpen::Face* face = faces[j];

                    // 获取面的所有边
                    std::vector<NXOpen::Edge*> edges = face->GetEdges();

                    // 遍历边的顶点找到最小Z值
                    for (size_t k = 0; k < edges.size(); k++)
                    {
                        NXOpen::Edge* edge = edges[k];
                        NXOpen::Point3d vertex1, vertex2;
                        edge->GetVertices(&vertex1, &vertex2);

                        if (vertex1.Z < minZ)
                        {
                            minZ = vertex1.Z;
                            bottomFace = face;
                        }
                        if (vertex2.Z < minZ)
                        {
                            minZ = vertex2.Z;
                            bottomFace = face;
                        }
                    }
                }

                if (bottomFace == NULL)
                {
                    continue;
                }

                // 计算需要移动的距离（将底面移动到Z=0）
                double moveDistance = -minZ;

                // 获取实体的tag
                tag_t bodyTag = body->Tag();

                // 使用UF函数移动特征
                // 获取实体的所有特征列表
                uf_list_p_t feature_list = NULL;
                UF_MODL_ask_body_feats(bodyTag, &feature_list);

                if (feature_list != NULL)
                {
                    // 设置移动数据（POINT_TO_POINT模式）
                    double real_data[2][12];
                    // 初始化所有数据为0
                    for (int m = 0; m < 2; m++)
                    {
                        for (int n = 0; n < 12; n++)
                        {
                            real_data[m][n] = 0.0;
                        }
                    }
                    // 初始点 (0, 0, 0)
                    real_data[0][0] = 0.0;
                    real_data[0][1] = 0.0;
                    real_data[0][2] = 0.0;
                    // 目标点 (0, 0, moveDistance)
                    real_data[1][0] = 0.0;
                    real_data[1][1] = 0.0;
                    real_data[1][2] = moveDistance;

                    // 移动特征
                    UF_MODL_move_feature(feature_list, 0, real_data);

                    // 更新部件
                    UF_MODL_update();

                    // 清理列表
                    UF_MODL_delete_list(&feature_list);
                }

                // 输出信息
                char msg[256];
                sprintf(msg, "实体已移动，Z方向移动距离: %f", moveDistance);
                uc1601(msg, 1);
            }

            UI1::theUI->NXMessageBox()->Show("完成", NXOpen::NXMessageBox::DialogTypeInformation, "实体对齐完成！");
        }

        // 功能3：指定点定位 - 如果用户指定了点，则移动整个排样组
        NXOpen::Point3d specifiedPoint;
        bool hasPoint = false;
        try {
            specifiedPoint = ui_point0->Point();
            // 简单判断点是否有效（非原点或用户确实设置了点）
            hasPoint = true;
        }
        catch (...) {
            hasPoint = false;
        }

        if (hasPoint && !movedBodies.empty())
        {
            theSession->ListingWindow()->WriteLine("=== 开始移动到指定点 ===");

            // 计算当前所有移动后实体的总包围盒
            double totalMinX = 1e30, totalMinY = 1e30, totalMinZ = 1e30;
            double totalMaxX = -1e30, totalMaxY = -1e30, totalMaxZ = -1e30;

            for (size_t i = 0; i < movedBodies.size(); i++)
            {
                tag_t bodyTag = movedBodies[i]->Tag();
                double box[6];
                UF_MODL_ask_bounding_box(bodyTag, box);

                if (box[0] < totalMinX) totalMinX = box[0];
                if (box[1] < totalMinY) totalMinY = box[1];
                if (box[2] < totalMinZ) totalMinZ = box[2];
                if (box[3] > totalMaxX) totalMaxX = box[3];
                if (box[4] > totalMaxY) totalMaxY = box[4];
                if (box[5] > totalMaxZ) totalMaxZ = box[5];
            }

            // 计算包围盒中心
            double centerX = (totalMinX + totalMaxX) / 2.0;
            double centerY = (totalMinY + totalMaxY) / 2.0;
            double centerZ = (totalMinZ + totalMaxZ) / 2.0;

            // 计算需要移动的距离（将包围盒中心移动到指定点）
            double moveX = specifiedPoint.X - centerX;
            double moveY = specifiedPoint.Y - centerY;
            double moveZ = specifiedPoint.Z - centerZ;

            theSession->ListingWindow()->WriteLine(NXString("移动到指定点: (" +
                std::to_string(specifiedPoint.X) + ", " +
                std::to_string(specifiedPoint.Y) + ", " +
                std::to_string(specifiedPoint.Z) + ")"));
            theSession->ListingWindow()->WriteLine(NXString("移动距离: dX=" +
                std::to_string(moveX) + ", dY=" +
                std::to_string(moveY) + ", dZ=" +
                std::to_string(moveZ)));

            // 使用UF_MODL_move_feature移动所有实体
            for (size_t i = 0; i < movedBodies.size(); i++)
            {
                tag_t bodyTag = movedBodies[i]->Tag();
                double box[6];
                UF_MODL_ask_bounding_box(bodyTag, box);

                // 获取实体的所有特征列表
                uf_list_p_t feature_list = NULL;
                UF_MODL_ask_body_feats(bodyTag, &feature_list);

                if (feature_list != NULL)
                {
                    // 设置移动数据（POINT_TO_POINT模式）
                    double real_data[2][12];
                    // 初始化所有数据为0
                    for (int m = 0; m < 2; m++)
                    {
                        for (int n = 0; n < 12; n++)
                        {
                            real_data[m][n] = 0.0;
                        }
                    }
                    // 初始点 (当前包围盒中心)
                    real_data[0][0] = centerX;
                    real_data[0][1] = centerY;
                    real_data[0][2] = centerZ;
                    // 目标点 (指定点)
                    real_data[1][0] = specifiedPoint.X;
                    real_data[1][1] = specifiedPoint.Y;
                    real_data[1][2] = specifiedPoint.Z;

                    // 移动特征
                    UF_MODL_move_feature(feature_list, 0, real_data);

                    // 清理列表
                    UF_MODL_delete_list(&feature_list);
                }
            }

            // 如果有包围盒，也一起移动
            if (boundingBoxBody != NULL)
            {
                tag_t bodyTag = boundingBoxBody->Tag();
                double box[6];
                UF_MODL_ask_bounding_box(bodyTag, box);

                // 获取实体的所有特征列表
                uf_list_p_t feature_list = NULL;
                UF_MODL_ask_body_feats(bodyTag, &feature_list);

                if (feature_list != NULL)
                {
                    // 设置移动数据（POINT_TO_POINT模式）
                    double real_data[2][12];
                    // 初始化所有数据为0
                    for (int m = 0; m < 2; m++)
                    {
                        for (int n = 0; n < 12; n++)
                        {
                            real_data[m][n] = 0.0;
                        }
                    }
                    // 初始点 (当前包围盒中心)
                    real_data[0][0] = centerX;
                    real_data[0][1] = centerY;
                    real_data[0][2] = centerZ;
                    // 目标点 (指定点)
                    real_data[1][0] = specifiedPoint.X;
                    real_data[1][1] = specifiedPoint.Y;
                    real_data[1][2] = specifiedPoint.Z;

                    // 移动特征
                    UF_MODL_move_feature(feature_list, 0, real_data);

                    // 清理列表
                    UF_MODL_delete_list(&feature_list);
                }
            }

            // 更新部件
            UF_MODL_update();

            theSession->ListingWindow()->WriteLine("=== 移动到指定点完成 ===");
        }
    }
    catch (exception& ex)
    {
        //---- Enter your exception handling code here -----
        errorCode = 1;
        UI1::theUI->NXMessageBox()->Show("Block Styler", NXOpen::NXMessageBox::DialogTypeError, ex.what());
    }
    return errorCode;
}
//Callback Name: update_cb
int UI1::update_cb(NXOpen::BlockStyler::UIBlock* block)
{
    try
    {
        if (block == ui_button0)
        {
            //---------Enter your code here-----------
        }
        else if (block == ui_selection0)
        {
            //---------Enter your code here-----------
        }
        else if (block == ui_point0)
        {
            //---------Enter your code here-----------
        }
        else if (block == ui_toggle0)
        {
            //---------Enter your code here-----------
        }
        else if (block == ui_linear_dim0)
        {
            //---------Enter your code here-----------
        }
        else if (block == ui_linear_dim01)
        {
            //---------Enter your code here-----------
        }
        else if (block == ui_linear_dim02)
        {
            //---------Enter your code here-----------
        }
        else if (block == ui_toggle01)
        {
            //---------Enter your code here-----------
        }
    }
    catch (exception& ex)
    {
        //---- Enter your exception handling code here -----
        UI1::theUI->NXMessageBox()->Show("Block Styler", NXOpen::NXMessageBox::DialogTypeError, ex.what());
    }
    return 0;
}
//Callback Name: ok_cb
int UI1::ok_cb()
{
    int errorCode = 0;
    try
    {
        errorCode = apply_cb();
    }
    catch (exception& ex)
    {
        //---- Enter your exception handling code here -----
        errorCode = 1;
        UI1::theUI->NXMessageBox()->Show("Block Styler", NXOpen::NXMessageBox::DialogTypeError, ex.what());
    }
    return errorCode;
}
//Function Name: GetBlockProperties
PropertyList* UI1::GetBlockProperties(const char* blockID)
{
    return theDialog->GetBlockProperties(blockID);
}
